spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myrtle_trip
    username: myrtle_app
    password: 1146Highland

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080