-- Golf Event Manager database baseline
--
-- Source: schema-only pg_dump of the known-good myrtle_trip database
-- Captured: 2026-10-01
-- PostgreSQL source version: 18.3
--
-- This migration intentionally contains schema only. It creates the complete
-- current database structure, including legacy/compatibility tables that are
-- not presently mapped by JPA.
--
-- Existing non-empty databases are introduced to Flyway using
-- baseline-on-migrate at version 1, so this migration is NOT replayed over
-- an existing schema. Fresh/empty databases execute this migration normally.

--
-- Name: contest_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contest_result (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    contest_type character varying(50),
    player_id bigint,
    rank integer,
    result_score numeric(10,2),
    payout numeric(10,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: contest_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contest_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contest_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    location character varying(150),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    legacy_course_number integer,
    address_line_1 character varying(150),
    address_line_2 character varying(150),
    city character varying(100),
    state character varying(50),
    postal_code character varying(20),
    phone_number character varying(40),
    website_url character varying(500)
);


--
-- Name: course_hole; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_hole (
    id bigint NOT NULL,
    course_tee_id bigint NOT NULL,
    hole_number integer NOT NULL,
    par integer,
    handicap integer,
    yardage integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    women_par integer,
    women_handicap integer
);


--
-- Name: course_hole_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_hole ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_hole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_tee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_tee (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    tee_name character varying(80) NOT NULL,
    course_rating numeric(5,2),
    slope integer,
    par_total integer NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    effective_date date NOT NULL,
    retired_date date,
    yardage_total integer,
    tee_type character varying(10) DEFAULT 'REGULAR'::character varying,
    women_course_rating numeric(5,2),
    women_slope integer,
    women_par_total integer
);


--
-- Name: course_tee_combo_hole; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_tee_combo_hole (
    id bigint NOT NULL,
    combo_tee_id bigint NOT NULL,
    hole_number integer NOT NULL,
    source_tee_id bigint NOT NULL
);


--
-- Name: course_tee_combo_hole_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.course_tee_combo_hole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: course_tee_combo_hole_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.course_tee_combo_hole_id_seq OWNED BY public.course_tee_combo_hole.id;


--
-- Name: course_tee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_tee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_tee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grouping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."grouping" (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    group_number integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tee_time time without time zone,
    starting_hole integer,
    CONSTRAINT ck_grouping_starting_hole CHECK (((starting_hole IS NULL) OR (starting_hole = ANY (ARRAY[1, 10]))))
);


--
-- Name: grouping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."grouping" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grouping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grouping_player; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grouping_player (
    id bigint NOT NULL,
    grouping_id bigint NOT NULL,
    player_id bigint NOT NULL,
    seat_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: grouping_player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grouping_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grouping_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hole_score; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hole_score (
    id bigint NOT NULL,
    scorecard_id bigint NOT NULL,
    hole_number integer NOT NULL,
    strokes integer,
    adjusted_strokes integer,
    net_strokes integer,
    used_in_team_game boolean,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: hole_score_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hole_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hole_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player (
    id bigint NOT NULL,
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    display_name character varying(120) NOT NULL,
    ghin_number character varying(32),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    email character varying(255),
    cell character varying(50),
    venmo_id character varying(100),
    zelle_id character varying(100),
    legacy_player_number integer,
    handicap_method character varying(30),
    gender character varying(1) DEFAULT 'M'::character varying NOT NULL,
    created_source character varying(25),
    created_by character varying(100),
    normalized_name character varying(200),
    normalized_email character varying(200),
    CONSTRAINT chk_player_gender CHECK (((gender)::text = ANY ((ARRAY['M'::character varying, 'F'::character varying])::text[])))
);


--
-- Name: player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_winnings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_winnings (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    player_id bigint NOT NULL,
    category character varying(60),
    amount numeric(10,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: player_winnings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.player_winnings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_winnings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prize_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prize_schedule (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    round_id bigint,
    game_key character varying(100) NOT NULL,
    game_name character varying(255) NOT NULL,
    result_scope character varying(20) NOT NULL,
    payout_unit character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: prize_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.prize_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prize_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.prize_schedule_id_seq OWNED BY public.prize_schedule.id;


--
-- Name: prize_schedule_payout; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prize_schedule_payout (
    id bigint NOT NULL,
    prize_schedule_id bigint NOT NULL,
    finishing_place integer NOT NULL,
    amount_per_player numeric(10,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: prize_schedule_payout_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.prize_schedule_payout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prize_schedule_payout_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.prize_schedule_payout_id_seq OWNED BY public.prize_schedule_payout.id;


--
-- Name: prize_winning; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prize_winning (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    round_id bigint,
    prize_schedule_id bigint NOT NULL,
    player_id bigint NOT NULL,
    game_key character varying(80) NOT NULL,
    game_name character varying(160) NOT NULL,
    source_rank integer,
    source_name character varying(160),
    amount numeric(10,2) DEFAULT 0 NOT NULL
);


--
-- Name: prize_winning_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.prize_winning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prize_winning_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.prize_winning_id_seq OWNED BY public.prize_winning.id;


--
-- Name: round; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    round_date date,
    finalized boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    format character varying(50) NOT NULL,
    course_id bigint,
    handicap_percent integer DEFAULT 100 NOT NULL,
    standard_round_tee_id bigint,
    alternate_round_tee_id bigint,
    round_number integer NOT NULL,
    default_round_tee_id bigint,
    team_size integer DEFAULT 4 NOT NULL,
    scramble_team_size integer DEFAULT 4 NOT NULL,
    scramble_seeding_method character varying(40) DEFAULT 'CURRENT_HANDICAP_INDEX'::character varying NOT NULL,
    scramble_score_entry_mode character varying(20),
    scramble_handicap_date date,
    CONSTRAINT ck_round_scramble_score_entry_mode CHECK (((scramble_score_entry_mode)::text = ANY ((ARRAY['TOTAL'::character varying, 'HOLES'::character varying])::text[]))),
    CONSTRAINT ck_round_scramble_seeding_method CHECK (((scramble_seeding_method)::text = ANY ((ARRAY['CURRENT_HANDICAP_INDEX'::character varying, 'AVERAGE_GROSS_SCORE'::character varying, 'AVERAGE_NET_SCORE'::character varying])::text[]))),
    CONSTRAINT ck_round_scramble_team_size CHECK ((scramble_team_size = ANY (ARRAY[2, 3, 4]))),
    CONSTRAINT ck_round_team_size CHECK ((team_size = ANY (ARRAY[1, 2, 3, 4])))
);


--
-- Name: round_correction_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_correction_log (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    player_id bigint,
    correction_type character varying(40) NOT NULL,
    previous_value text,
    new_value text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(120)
);


--
-- Name: round_correction_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_correction_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_correction_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_correction_log_id_seq OWNED BY public.round_correction_log.id;


--
-- Name: round_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_event (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    event_name character varying(100) NOT NULL,
    event_order integer DEFAULT 1 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    uses_gross boolean DEFAULT false NOT NULL,
    uses_net boolean DEFAULT false NOT NULL,
    uses_teams boolean DEFAULT false NOT NULL,
    team_size integer,
    handicap_percent integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: round_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_event_id_seq OWNED BY public.round_event.id;


--
-- Name: round_hole_score; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_hole_score (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    hole_number integer NOT NULL,
    strokes integer NOT NULL
);


--
-- Name: round_hole_score_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_hole_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_hole_score_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_hole_score_id_seq OWNED BY public.round_hole_score.id;


--
-- Name: round_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.round ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: round_scramble_seed_round; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_scramble_seed_round (
    id bigint NOT NULL,
    scramble_round_id bigint NOT NULL,
    planned_round_id bigint NOT NULL
);


--
-- Name: round_scramble_seed_round_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_scramble_seed_round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_scramble_seed_round_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_scramble_seed_round_id_seq OWNED BY public.round_scramble_seed_round.id;


--
-- Name: round_team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_team (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    team_number integer NOT NULL,
    team_name character varying(255),
    scramble_total_score integer,
    CONSTRAINT chk_round_team_scramble_total_score CHECK (((scramble_total_score IS NULL) OR ((scramble_total_score >= 1) AND (scramble_total_score <= 200))))
);


--
-- Name: round_team_exception; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_team_exception (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    round_team_id bigint NOT NULL,
    exception_type character varying(40) NOT NULL,
    ghost_player_id bigint,
    ghost_source_team_id bigint,
    index_min numeric(5,2),
    index_max numeric(5,2),
    selection_method character varying(20),
    rotation_pattern character varying(200),
    active boolean DEFAULT true NOT NULL,
    notes character varying(500)
);


--
-- Name: round_team_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_team_exception_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_team_exception_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_team_exception_id_seq OWNED BY public.round_team_exception.id;


--
-- Name: round_team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.round_team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: round_team_player; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_team_player (
    id bigint NOT NULL,
    round_team_id bigint NOT NULL,
    player_id bigint NOT NULL,
    player_order integer
);


--
-- Name: round_team_player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.round_team_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_team_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: round_tee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_tee (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    source_course_tee_id bigint,
    tee_role character varying(20) NOT NULL,
    course_name character varying(150) NOT NULL,
    tee_name character varying(80) NOT NULL,
    course_rating numeric(5,2) NOT NULL,
    slope integer NOT NULL,
    par_total integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_round_tee_role CHECK (((tee_role)::text = ANY ((ARRAY['DEFAULT'::character varying, 'PLAYER_OPTION'::character varying])::text[])))
);


--
-- Name: round_tee_hole; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_tee_hole (
    id bigint NOT NULL,
    round_tee_id bigint NOT NULL,
    hole_number integer NOT NULL,
    par integer NOT NULL,
    handicap integer NOT NULL,
    yardage integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: round_tee_hole_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.round_tee_hole ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_tee_hole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: round_tee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.round_tee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_tee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: score_history_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.score_history_entry (
    id bigint NOT NULL,
    player_id bigint NOT NULL,
    score_date date NOT NULL,
    course_name character varying(150) NOT NULL,
    course_rating numeric(5,2) NOT NULL,
    slope integer NOT NULL,
    gross_score integer,
    adjusted_gross_score integer,
    differential numeric(6,3),
    source_type character varying(40),
    included_in_myrtle_calc boolean DEFAULT true,
    round_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    course_id bigint,
    handicap_group_code character varying(50),
    posting_order integer,
    score_type character varying(10),
    holes_played integer,
    manual_differential_required boolean NOT NULL,
    tee_name character varying(80),
    par_total integer,
    round_tee_id bigint
);


--
-- Name: score_history_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.score_history_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.score_history_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scorecard; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scorecard (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    player_id bigint NOT NULL,
    course_handicap integer,
    playing_handicap integer,
    gross_score integer,
    adjusted_gross_score integer,
    net_score integer,
    thru_hole integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    team_id bigint,
    round_tee_id bigint,
    participation_status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    withdrawal_hole_number integer,
    CONSTRAINT chk_scorecard_withdrawal_hole_number CHECK (((withdrawal_hole_number IS NULL) OR ((withdrawal_hole_number >= 0) AND (withdrawal_hole_number <= 18))))
);


--
-- Name: scorecard_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scorecard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scorecard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team (
    id bigint NOT NULL,
    round_id bigint NOT NULL,
    team_number integer NOT NULL,
    team_name character varying(100),
    team_type character varying(40) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: team_hole_score; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_hole_score (
    id bigint NOT NULL,
    round_team_id bigint NOT NULL,
    hole_number integer NOT NULL,
    strokes integer NOT NULL
);


--
-- Name: team_hole_score_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_hole_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_hole_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_player; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_player (
    id bigint NOT NULL,
    team_id bigint NOT NULL,
    player_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: team_player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    trip_year integer NOT NULL,
    start_date date,
    end_date date,
    status character varying(30) DEFAULT 'PLANNING'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    trip_code character varying(50) NOT NULL,
    initialized boolean DEFAULT false,
    entry_fee integer,
    correction_mode boolean DEFAULT false NOT NULL,
    handicap_method character varying(40) DEFAULT 'GHIN_PLUS_DB_SCORE_HISTORY'::character varying NOT NULL,
    handicaps_enabled boolean DEFAULT true NOT NULL,
    trip_start_date date,
    trip_end_date date,
    planned_round_count integer DEFAULT 5 NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    archived_at timestamp without time zone,
    CONSTRAINT ck_trip_date_range CHECK (((trip_start_date IS NULL) OR (trip_end_date IS NULL) OR (trip_start_date <= trip_end_date))),
    CONSTRAINT ck_trip_planned_round_count CHECK (((planned_round_count >= 1) AND (planned_round_count <= 20)))
);


--
-- Name: trip_bill_inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_bill_inventory (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    hundreds_count integer DEFAULT 0 NOT NULL,
    fifties_count integer DEFAULT 0 NOT NULL,
    twenties_count integer DEFAULT 0 NOT NULL,
    tens_count integer DEFAULT 0 NOT NULL,
    fives_count integer DEFAULT 0 NOT NULL,
    ones_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_trip_bill_inventory_nonnegative CHECK (((hundreds_count >= 0) AND (fifties_count >= 0) AND (twenties_count >= 0) AND (tens_count >= 0) AND (fives_count >= 0) AND (ones_count >= 0)))
);


--
-- Name: trip_bill_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_bill_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_bill_inventory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_bill_inventory_id_seq OWNED BY public.trip_bill_inventory.id;


--
-- Name: trip_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_planned_round; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_planned_round (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    round_number integer NOT NULL,
    round_date date,
    course_id bigint,
    format character varying(50),
    standard_tee_id bigint,
    include_in_four_day_standings boolean DEFAULT false NOT NULL,
    scramble_team_size integer DEFAULT 4 NOT NULL,
    women_default_tee_id bigint,
    CONSTRAINT ck_trip_planned_round_scramble_team_size CHECK ((scramble_team_size = ANY (ARRAY[2, 3, 4])))
);


--
-- Name: trip_planned_round_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_planned_round_event (
    id bigint NOT NULL,
    planned_round_id bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    event_name character varying(100) NOT NULL,
    event_order integer DEFAULT 1 NOT NULL,
    team_size integer,
    handicap_percent integer
);


--
-- Name: trip_planned_round_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_planned_round_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_planned_round_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_planned_round_event_id_seq OWNED BY public.trip_planned_round_event.id;


--
-- Name: trip_planned_round_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_planned_round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_planned_round_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_planned_round_id_seq OWNED BY public.trip_planned_round.id;


--
-- Name: trip_player; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_player (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    player_id bigint NOT NULL,
    display_order integer NOT NULL,
    starting_handicap_index numeric(5,2),
    current_handicap_index numeric(5,2),
    current_myrtle_handicap numeric(5,2),
    notes character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    frozen_handicap_index numeric(5,1),
    participation_status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL
);


--
-- Name: trip_player_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trip_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_player_payout_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_player_payout_status (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    player_id bigint NOT NULL,
    paid boolean DEFAULT false NOT NULL,
    paid_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: trip_player_payout_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_player_payout_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_player_payout_status_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_player_payout_status_id_seq OWNED BY public.trip_player_payout_status.id;


--
-- Name: trip_tournament; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_tournament (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    name character varying(160) DEFAULT 'Multi-Round Tournament'::character varying NOT NULL,
    standings_label character varying(160) DEFAULT 'Tournament Standings'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    low_net_enabled boolean DEFAULT true NOT NULL,
    low_gross_enabled boolean DEFAULT false NOT NULL,
    low_net_name character varying(160) DEFAULT '2-Round Low Net'::character varying NOT NULL,
    low_gross_name character varying(160) DEFAULT '2-Round Low Gross'::character varying NOT NULL
);


--
-- Name: trip_tournament_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_tournament_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_tournament_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_tournament_id_seq OWNED BY public.trip_tournament.id;


--
-- Name: trip_tournament_round; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_tournament_round (
    id bigint NOT NULL,
    tournament_id bigint NOT NULL,
    planned_round_id bigint NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: trip_tournament_round_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_tournament_round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_tournament_round_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_tournament_round_id_seq OWNED BY public.trip_tournament_round.id;


--
-- Name: course_tee_combo_hole id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee_combo_hole ALTER COLUMN id SET DEFAULT nextval('public.course_tee_combo_hole_id_seq'::regclass);


--
-- Name: prize_schedule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule ALTER COLUMN id SET DEFAULT nextval('public.prize_schedule_id_seq'::regclass);


--
-- Name: prize_schedule_payout id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule_payout ALTER COLUMN id SET DEFAULT nextval('public.prize_schedule_payout_id_seq'::regclass);


--
-- Name: prize_winning id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning ALTER COLUMN id SET DEFAULT nextval('public.prize_winning_id_seq'::regclass);


--
-- Name: round_correction_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_correction_log ALTER COLUMN id SET DEFAULT nextval('public.round_correction_log_id_seq'::regclass);


--
-- Name: round_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_event ALTER COLUMN id SET DEFAULT nextval('public.round_event_id_seq'::regclass);


--
-- Name: round_hole_score id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_hole_score ALTER COLUMN id SET DEFAULT nextval('public.round_hole_score_id_seq'::regclass);


--
-- Name: round_scramble_seed_round id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_scramble_seed_round ALTER COLUMN id SET DEFAULT nextval('public.round_scramble_seed_round_id_seq'::regclass);


--
-- Name: round_team_exception id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception ALTER COLUMN id SET DEFAULT nextval('public.round_team_exception_id_seq'::regclass);


--
-- Name: trip_bill_inventory id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_bill_inventory ALTER COLUMN id SET DEFAULT nextval('public.trip_bill_inventory_id_seq'::regclass);


--
-- Name: trip_planned_round id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round ALTER COLUMN id SET DEFAULT nextval('public.trip_planned_round_id_seq'::regclass);


--
-- Name: trip_planned_round_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round_event ALTER COLUMN id SET DEFAULT nextval('public.trip_planned_round_event_id_seq'::regclass);


--
-- Name: trip_player_payout_status id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player_payout_status ALTER COLUMN id SET DEFAULT nextval('public.trip_player_payout_status_id_seq'::regclass);


--
-- Name: trip_tournament id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament ALTER COLUMN id SET DEFAULT nextval('public.trip_tournament_id_seq'::regclass);


--
-- Name: trip_tournament_round id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round ALTER COLUMN id SET DEFAULT nextval('public.trip_tournament_round_id_seq'::regclass);


--
-- Name: contest_result contest_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_result
    ADD CONSTRAINT contest_result_pkey PRIMARY KEY (id);


--
-- Name: course_hole course_hole_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_hole
    ADD CONSTRAINT course_hole_pkey PRIMARY KEY (id);


--
-- Name: course course_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_name_key UNIQUE (name);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: course_tee_combo_hole course_tee_combo_hole_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee_combo_hole
    ADD CONSTRAINT course_tee_combo_hole_pkey PRIMARY KEY (id);


--
-- Name: course_tee course_tee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee
    ADD CONSTRAINT course_tee_pkey PRIMARY KEY (id);


--
-- Name: grouping grouping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."grouping"
    ADD CONSTRAINT grouping_pkey PRIMARY KEY (id);


--
-- Name: grouping_player grouping_player_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grouping_player
    ADD CONSTRAINT grouping_player_pkey PRIMARY KEY (id);


--
-- Name: hole_score hole_score_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hole_score
    ADD CONSTRAINT hole_score_pkey PRIMARY KEY (id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: player_winnings player_winnings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_winnings
    ADD CONSTRAINT player_winnings_pkey PRIMARY KEY (id);


--
-- Name: prize_schedule_payout prize_schedule_payout_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule_payout
    ADD CONSTRAINT prize_schedule_payout_pkey PRIMARY KEY (id);


--
-- Name: prize_schedule prize_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule
    ADD CONSTRAINT prize_schedule_pkey PRIMARY KEY (id);


--
-- Name: prize_winning prize_winning_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning
    ADD CONSTRAINT prize_winning_pkey PRIMARY KEY (id);


--
-- Name: round_correction_log round_correction_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_correction_log
    ADD CONSTRAINT round_correction_log_pkey PRIMARY KEY (id);


--
-- Name: round_event round_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_event
    ADD CONSTRAINT round_event_pkey PRIMARY KEY (id);


--
-- Name: round_hole_score round_hole_score_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_hole_score
    ADD CONSTRAINT round_hole_score_pkey PRIMARY KEY (id);


--
-- Name: round round_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT round_pkey PRIMARY KEY (id);


--
-- Name: round_scramble_seed_round round_scramble_seed_round_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_scramble_seed_round
    ADD CONSTRAINT round_scramble_seed_round_pkey PRIMARY KEY (id);


--
-- Name: round_team_exception round_team_exception_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception
    ADD CONSTRAINT round_team_exception_pkey PRIMARY KEY (id);


--
-- Name: round_team round_team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team
    ADD CONSTRAINT round_team_pkey PRIMARY KEY (id);


--
-- Name: round_team_player round_team_player_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_player
    ADD CONSTRAINT round_team_player_pkey PRIMARY KEY (id);


--
-- Name: round_tee_hole round_tee_hole_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee_hole
    ADD CONSTRAINT round_tee_hole_pkey PRIMARY KEY (id);


--
-- Name: round_tee round_tee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee
    ADD CONSTRAINT round_tee_pkey PRIMARY KEY (id);


--
-- Name: score_history_entry score_history_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT score_history_entry_pkey PRIMARY KEY (id);


--
-- Name: scorecard scorecard_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT scorecard_pkey PRIMARY KEY (id);


--
-- Name: team_hole_score team_hole_score_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_hole_score
    ADD CONSTRAINT team_hole_score_pkey PRIMARY KEY (id);


--
-- Name: team team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);


--
-- Name: team_player team_player_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT team_player_pkey PRIMARY KEY (id);


--
-- Name: trip_bill_inventory trip_bill_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_bill_inventory
    ADD CONSTRAINT trip_bill_inventory_pkey PRIMARY KEY (id);


--
-- Name: trip trip_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip
    ADD CONSTRAINT trip_pkey PRIMARY KEY (id);


--
-- Name: trip_planned_round_event trip_planned_round_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round_event
    ADD CONSTRAINT trip_planned_round_event_pkey PRIMARY KEY (id);


--
-- Name: trip_planned_round trip_planned_round_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round
    ADD CONSTRAINT trip_planned_round_pkey PRIMARY KEY (id);


--
-- Name: trip_player_payout_status trip_player_payout_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player_payout_status
    ADD CONSTRAINT trip_player_payout_status_pkey PRIMARY KEY (id);


--
-- Name: trip_player trip_player_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player
    ADD CONSTRAINT trip_player_pkey PRIMARY KEY (id);


--
-- Name: trip_tournament trip_tournament_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament
    ADD CONSTRAINT trip_tournament_pkey PRIMARY KEY (id);


--
-- Name: trip_tournament_round trip_tournament_round_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round
    ADD CONSTRAINT trip_tournament_round_pkey PRIMARY KEY (id);


--
-- Name: course uk_course_legacy_course_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT uk_course_legacy_course_number UNIQUE (legacy_course_number);


--
-- Name: round_event uk_round_event_round_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_event
    ADD CONSTRAINT uk_round_event_round_order UNIQUE (round_id, event_order);


--
-- Name: round_event uk_round_event_round_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_event
    ADD CONSTRAINT uk_round_event_round_type UNIQUE (round_id, event_type);


--
-- Name: round_hole_score uk_round_hole_score_round_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_hole_score
    ADD CONSTRAINT uk_round_hole_score_round_hole UNIQUE (round_id, hole_number);


--
-- Name: round_scramble_seed_round uk_round_scramble_seed_round; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_scramble_seed_round
    ADD CONSTRAINT uk_round_scramble_seed_round UNIQUE (scramble_round_id, planned_round_id);


--
-- Name: score_history_entry uk_score_history_round_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT uk_score_history_round_player UNIQUE (round_id, player_id);


--
-- Name: team_hole_score uk_team_hole_score_team_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_hole_score
    ADD CONSTRAINT uk_team_hole_score_team_hole UNIQUE (round_team_id, hole_number);


--
-- Name: trip_bill_inventory uk_trip_bill_inventory_trip; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_bill_inventory
    ADD CONSTRAINT uk_trip_bill_inventory_trip UNIQUE (trip_id);


--
-- Name: trip uk_trip_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip
    ADD CONSTRAINT uk_trip_code UNIQUE (trip_code);


--
-- Name: trip_planned_round uk_trip_planned_round_trip_round; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round
    ADD CONSTRAINT uk_trip_planned_round_trip_round UNIQUE (trip_id, round_number);


--
-- Name: trip_player_payout_status uk_trip_player_payout_status_trip_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player_payout_status
    ADD CONSTRAINT uk_trip_player_payout_status_trip_player UNIQUE (trip_id, player_id);


--
-- Name: trip_tournament_round uk_trip_tournament_round_planned; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round
    ADD CONSTRAINT uk_trip_tournament_round_planned UNIQUE (tournament_id, planned_round_id);


--
-- Name: trip_tournament_round uk_trip_tournament_round_sort; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round
    ADD CONSTRAINT uk_trip_tournament_round_sort UNIQUE (tournament_id, sort_order);


--
-- Name: trip_tournament uk_trip_tournament_trip; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament
    ADD CONSTRAINT uk_trip_tournament_trip UNIQUE (trip_id);


--
-- Name: course_tee_combo_hole uq_combo_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee_combo_hole
    ADD CONSTRAINT uq_combo_hole UNIQUE (combo_tee_id, hole_number);


--
-- Name: course_hole uq_course_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_hole
    ADD CONSTRAINT uq_course_hole UNIQUE (course_tee_id, hole_number);


--
-- Name: course_tee uq_course_tee_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee
    ADD CONSTRAINT uq_course_tee_version UNIQUE (course_id, tee_name, effective_date);


--
-- Name: grouping_player uq_grouping_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grouping_player
    ADD CONSTRAINT uq_grouping_player UNIQUE (grouping_id, player_id);


--
-- Name: grouping uq_grouping_round_group; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."grouping"
    ADD CONSTRAINT uq_grouping_round_group UNIQUE (round_id, group_number);


--
-- Name: grouping_player uq_grouping_seat_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grouping_player
    ADD CONSTRAINT uq_grouping_seat_order UNIQUE (grouping_id, seat_order);


--
-- Name: hole_score uq_hole_score_scorecard_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hole_score
    ADD CONSTRAINT uq_hole_score_scorecard_hole UNIQUE (scorecard_id, hole_number);


--
-- Name: prize_schedule_payout uq_prize_schedule_payout_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule_payout
    ADD CONSTRAINT uq_prize_schedule_payout_place UNIQUE (prize_schedule_id, finishing_place);


--
-- Name: prize_schedule uq_prize_schedule_trip_game; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule
    ADD CONSTRAINT uq_prize_schedule_trip_game UNIQUE (trip_id, game_key);


--
-- Name: round_tee_hole uq_round_tee_hole; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee_hole
    ADD CONSTRAINT uq_round_tee_hole UNIQUE (round_tee_id, hole_number);


--
-- Name: round uq_round_trip_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT uq_round_trip_number UNIQUE (trip_id, round_number);


--
-- Name: scorecard uq_scorecard_round_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT uq_scorecard_round_player UNIQUE (round_id, player_id);


--
-- Name: team_player uq_team_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT uq_team_player UNIQUE (team_id, player_id);


--
-- Name: team uq_team_round_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT uq_team_round_number UNIQUE (round_id, team_number);


--
-- Name: trip_player uq_trip_display_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player
    ADD CONSTRAINT uq_trip_display_order UNIQUE (trip_id, display_order);


--
-- Name: trip_player uq_trip_player; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player
    ADD CONSTRAINT uq_trip_player UNIQUE (trip_id, player_id);


--
-- Name: idx_prize_winning_trip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prize_winning_trip ON public.prize_winning USING btree (trip_id);


--
-- Name: idx_prize_winning_trip_game; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prize_winning_trip_game ON public.prize_winning USING btree (trip_id, game_key);


--
-- Name: idx_prize_winning_trip_player; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prize_winning_trip_player ON public.prize_winning USING btree (trip_id, player_id);


--
-- Name: idx_round_correction_log_player; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_correction_log_player ON public.round_correction_log USING btree (player_id);


--
-- Name: idx_round_correction_log_round_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_correction_log_round_created ON public.round_correction_log USING btree (round_id, created_at DESC, id DESC);


--
-- Name: idx_round_scramble_seed_round_planned_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_scramble_seed_round_planned_round ON public.round_scramble_seed_round USING btree (planned_round_id);


--
-- Name: idx_round_scramble_seed_round_scramble_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_scramble_seed_round_scramble_round ON public.round_scramble_seed_round USING btree (scramble_round_id);


--
-- Name: idx_round_team_exception_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_team_exception_round ON public.round_team_exception USING btree (round_id);


--
-- Name: idx_round_team_exception_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_round_team_exception_team ON public.round_team_exception USING btree (round_team_id);


--
-- Name: idx_score_history_entry_group_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_score_history_entry_group_code ON public.score_history_entry USING btree (handicap_group_code);


--
-- Name: idx_score_history_entry_group_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_score_history_entry_group_source ON public.score_history_entry USING btree (handicap_group_code, source_type);


--
-- Name: idx_score_history_entry_player_group; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_score_history_entry_player_group ON public.score_history_entry USING btree (player_id, handicap_group_code);


--
-- Name: idx_team_hole_score_round_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_team_hole_score_round_team ON public.team_hole_score USING btree (round_team_id);


--
-- Name: ix_round_event_round_active_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_round_event_round_active_order ON public.round_event USING btree (round_id, active, event_order);


--
-- Name: ix_round_event_round_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_round_event_round_id ON public.round_event USING btree (round_id);


--
-- Name: ix_round_scramble_seed_round_planned_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_round_scramble_seed_round_planned_round ON public.round_scramble_seed_round USING btree (planned_round_id);


--
-- Name: ix_round_scramble_seed_round_scramble_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_round_scramble_seed_round_scramble_round ON public.round_scramble_seed_round USING btree (scramble_round_id);


--
-- Name: uk_trip_planned_round_event_round_order; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_trip_planned_round_event_round_order ON public.trip_planned_round_event USING btree (planned_round_id, event_order);


--
-- Name: uk_trip_planned_round_event_round_type; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_trip_planned_round_event_round_type ON public.trip_planned_round_event USING btree (planned_round_id, event_type);


--
-- Name: uq_round_tee_round_source_course_tee; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_round_tee_round_source_course_tee ON public.round_tee USING btree (round_id, source_course_tee_id) WHERE (source_course_tee_id IS NOT NULL);


--
-- Name: ux_round_team_exception_one_ghost_use; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_round_team_exception_one_ghost_use ON public.round_team_exception USING btree (round_id, ghost_player_id) WHERE ((active = true) AND ((exception_type)::text = 'GHOST_PLAYER'::text) AND (ghost_player_id IS NOT NULL));


--
-- Name: ux_round_team_exception_one_type_per_team; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_round_team_exception_one_type_per_team ON public.round_team_exception USING btree (round_team_id, exception_type) WHERE (active = true);


--
-- Name: contest_result contest_result_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_result
    ADD CONSTRAINT contest_result_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: contest_result contest_result_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_result
    ADD CONSTRAINT contest_result_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: course_hole course_hole_course_tee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_hole
    ADD CONSTRAINT course_hole_course_tee_id_fkey FOREIGN KEY (course_tee_id) REFERENCES public.course_tee(id) ON DELETE CASCADE;


--
-- Name: course_tee course_tee_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee
    ADD CONSTRAINT course_tee_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON DELETE CASCADE;


--
-- Name: course_tee_combo_hole fk_combo_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee_combo_hole
    ADD CONSTRAINT fk_combo_tee FOREIGN KEY (combo_tee_id) REFERENCES public.course_tee(id);


--
-- Name: round fk_round_alternate_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT fk_round_alternate_round_tee FOREIGN KEY (alternate_round_tee_id) REFERENCES public.round_tee(id);


--
-- Name: round fk_round_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT fk_round_course FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: round fk_round_default_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT fk_round_default_round_tee FOREIGN KEY (default_round_tee_id) REFERENCES public.round_tee(id);


--
-- Name: round_hole_score fk_round_hole_score_round; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_hole_score
    ADD CONSTRAINT fk_round_hole_score_round FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: round_scramble_seed_round fk_round_scramble_seed_round_planned_round; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_scramble_seed_round
    ADD CONSTRAINT fk_round_scramble_seed_round_planned_round FOREIGN KEY (planned_round_id) REFERENCES public.trip_planned_round(id) ON DELETE CASCADE;


--
-- Name: round_scramble_seed_round fk_round_scramble_seed_round_round; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_scramble_seed_round
    ADD CONSTRAINT fk_round_scramble_seed_round_round FOREIGN KEY (scramble_round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: round fk_round_standard_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT fk_round_standard_round_tee FOREIGN KEY (standard_round_tee_id) REFERENCES public.round_tee(id);


--
-- Name: round_team_player fk_round_team_player_player; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_player
    ADD CONSTRAINT fk_round_team_player_player FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: round_team_player fk_round_team_player_team; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_player
    ADD CONSTRAINT fk_round_team_player_team FOREIGN KEY (round_team_id) REFERENCES public.round_team(id);


--
-- Name: round_team fk_round_team_round; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team
    ADD CONSTRAINT fk_round_team_round FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: round_tee_hole fk_round_tee_hole_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee_hole
    ADD CONSTRAINT fk_round_tee_hole_round_tee FOREIGN KEY (round_tee_id) REFERENCES public.round_tee(id) ON DELETE CASCADE;


--
-- Name: round_tee fk_round_tee_round; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee
    ADD CONSTRAINT fk_round_tee_round FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: round_tee fk_round_tee_source_course_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_tee
    ADD CONSTRAINT fk_round_tee_source_course_tee FOREIGN KEY (source_course_tee_id) REFERENCES public.course_tee(id);


--
-- Name: score_history_entry fk_score_history_entry_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT fk_score_history_entry_course FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: score_history_entry fk_score_history_entry_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT fk_score_history_entry_round_tee FOREIGN KEY (round_tee_id) REFERENCES public.round_tee(id);


--
-- Name: scorecard fk_scorecard_round_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT fk_scorecard_round_tee FOREIGN KEY (round_tee_id) REFERENCES public.round_tee(id);


--
-- Name: scorecard fk_scorecard_team; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT fk_scorecard_team FOREIGN KEY (team_id) REFERENCES public.round_team(id);


--
-- Name: course_tee_combo_hole fk_source_tee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tee_combo_hole
    ADD CONSTRAINT fk_source_tee FOREIGN KEY (source_tee_id) REFERENCES public.course_tee(id);


--
-- Name: team_hole_score fk_team_hole_score_round_team; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_hole_score
    ADD CONSTRAINT fk_team_hole_score_round_team FOREIGN KEY (round_team_id) REFERENCES public.round_team(id);


--
-- Name: trip_bill_inventory fk_trip_bill_inventory_trip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_bill_inventory
    ADD CONSTRAINT fk_trip_bill_inventory_trip FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: trip_planned_round fk_trip_planned_round_trip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round
    ADD CONSTRAINT fk_trip_planned_round_trip FOREIGN KEY (trip_id) REFERENCES public.trip(id);


--
-- Name: trip_tournament_round fk_trip_tournament_round_planned; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round
    ADD CONSTRAINT fk_trip_tournament_round_planned FOREIGN KEY (planned_round_id) REFERENCES public.trip_planned_round(id) ON DELETE CASCADE;


--
-- Name: trip_tournament_round fk_trip_tournament_round_tournament; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament_round
    ADD CONSTRAINT fk_trip_tournament_round_tournament FOREIGN KEY (tournament_id) REFERENCES public.trip_tournament(id) ON DELETE CASCADE;


--
-- Name: trip_tournament fk_trip_tournament_trip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_tournament
    ADD CONSTRAINT fk_trip_tournament_trip FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: grouping_player grouping_player_grouping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grouping_player
    ADD CONSTRAINT grouping_player_grouping_id_fkey FOREIGN KEY (grouping_id) REFERENCES public."grouping"(id) ON DELETE CASCADE;


--
-- Name: grouping_player grouping_player_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grouping_player
    ADD CONSTRAINT grouping_player_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: grouping grouping_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."grouping"
    ADD CONSTRAINT grouping_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: hole_score hole_score_scorecard_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hole_score
    ADD CONSTRAINT hole_score_scorecard_id_fkey FOREIGN KEY (scorecard_id) REFERENCES public.scorecard(id) ON DELETE CASCADE;


--
-- Name: player_winnings player_winnings_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_winnings
    ADD CONSTRAINT player_winnings_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: player_winnings player_winnings_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_winnings
    ADD CONSTRAINT player_winnings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: prize_schedule_payout prize_schedule_payout_prize_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule_payout
    ADD CONSTRAINT prize_schedule_payout_prize_schedule_id_fkey FOREIGN KEY (prize_schedule_id) REFERENCES public.prize_schedule(id) ON DELETE CASCADE;


--
-- Name: prize_schedule prize_schedule_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule
    ADD CONSTRAINT prize_schedule_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: prize_schedule prize_schedule_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_schedule
    ADD CONSTRAINT prize_schedule_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id);


--
-- Name: prize_winning prize_winning_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning
    ADD CONSTRAINT prize_winning_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: prize_winning prize_winning_prize_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning
    ADD CONSTRAINT prize_winning_prize_schedule_id_fkey FOREIGN KEY (prize_schedule_id) REFERENCES public.prize_schedule(id);


--
-- Name: prize_winning prize_winning_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning
    ADD CONSTRAINT prize_winning_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: prize_winning prize_winning_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prize_winning
    ADD CONSTRAINT prize_winning_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id);


--
-- Name: round_correction_log round_correction_log_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_correction_log
    ADD CONSTRAINT round_correction_log_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: round_correction_log round_correction_log_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_correction_log
    ADD CONSTRAINT round_correction_log_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: round_event round_event_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_event
    ADD CONSTRAINT round_event_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: round_team_exception round_team_exception_ghost_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception
    ADD CONSTRAINT round_team_exception_ghost_player_id_fkey FOREIGN KEY (ghost_player_id) REFERENCES public.player(id);


--
-- Name: round_team_exception round_team_exception_ghost_source_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception
    ADD CONSTRAINT round_team_exception_ghost_source_team_id_fkey FOREIGN KEY (ghost_source_team_id) REFERENCES public.round_team(id);


--
-- Name: round_team_exception round_team_exception_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception
    ADD CONSTRAINT round_team_exception_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: round_team_exception round_team_exception_round_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_team_exception
    ADD CONSTRAINT round_team_exception_round_team_id_fkey FOREIGN KEY (round_team_id) REFERENCES public.round_team(id);


--
-- Name: round round_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT round_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: score_history_entry score_history_entry_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT score_history_entry_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id) ON DELETE CASCADE;


--
-- Name: score_history_entry score_history_entry_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.score_history_entry
    ADD CONSTRAINT score_history_entry_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE SET NULL;


--
-- Name: scorecard scorecard_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT scorecard_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: scorecard scorecard_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scorecard
    ADD CONSTRAINT scorecard_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: team_player team_player_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT team_player_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: team_player team_player_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT team_player_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.team(id) ON DELETE CASCADE;


--
-- Name: team team_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: trip_planned_round_event trip_planned_round_event_planned_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_planned_round_event
    ADD CONSTRAINT trip_planned_round_event_planned_round_id_fkey FOREIGN KEY (planned_round_id) REFERENCES public.trip_planned_round(id) ON DELETE CASCADE;


--
-- Name: trip_player_payout_status trip_player_payout_status_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player_payout_status
    ADD CONSTRAINT trip_player_payout_status_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: trip_player_payout_status trip_player_payout_status_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player_payout_status
    ADD CONSTRAINT trip_player_payout_status_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id);


--
-- Name: trip_player trip_player_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player
    ADD CONSTRAINT trip_player_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: trip_player trip_player_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_player
    ADD CONSTRAINT trip_player_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;
